import { PageHeader } from '@/components/page-header';

export default function DisclaimerPage() {
  return (
    <div className="container mx-auto p-4 sm:p-6 md:p-8 lg:p-12">
      <PageHeader title="Disclaimer" />
      <div className="prose dark:prose-invert max-w-none space-y-4">
        <p>
          The information provided by Momentum AI ("we," "us," or "our") on this
          website is for general informational purposes only. All information on
          the Site is provided in a good faith, however we make no representation
          or warranty of any kind, express or implied, regarding the accuracy,
          adequacy, validity, reliability, availability or completeness of any
          information on the Site.
        </p>
        <p>
          The AI agents provided on this platform generate content based on
          complex algorithms and vast datasets. While we strive for accuracy and
          relevance, the generated content may not always be perfect and may
          sometimes produce incorrect or nonsensical information. We do not
          guarantee the reliability, accuracy, or completeness of the content
          generated by the AI.
        </p>
        <p>
          Under no circumstance shall we have any liability to you for any loss
          or damage of any kind incurred as a result of the use of the site or
          reliance on any information provided on the site. Your use of the site
          and your reliance on any information on the site is solely at your own
          risk.
        </p>
        <h2 className="text-2xl font-bold">External Links Disclaimer</h2>
        <p>
          The Site may contain (or you may be sent through the Site) links to
          other websites or content belonging to or originating from third
          parties or links to websites and features in banners or other
          advertising. Such external links are not investigated, monitored, or
          checked for accuracy, adequacy, validity, reliability, availability or
          completeness by us.
        </p>
        <h2 className="text-2xl font-bold">Professional Disclaimer</h2>
        <p>
          The Site cannot and does not contain professional advice. The
          information is provided for general informational and educational
          purposes only and is not a substitute for professional advice.
          Accordingly, before taking any actions based upon such information, we
          encourage you to consult with the appropriate professionals. We do not
          provide any kind of professional advice. The use or reliance of any
          information contained on this site is solely at your own risk.
        </p>
      </div>
    </div>
  );
}
